rust:
    directory: ./rust
    manifestPath: Cargo.toml
android:
    directory: ./android
    cargoExtras: []
    targets:
    - arm64-v8a
    - armeabi-v7a
    - x86
    - x86_64
    apiLevel: 24
    jniLibs: src/main/jniLibs
    useSharedLibrary: true